[package]
authors = ["Pietro Lorefice <pietro.lorefice@gmail.com>"]
description = "A Game Boy emulator written in Rust"
edition = "2018"
name = "gib"
version = "0.5.2"

[workspace]
members = ["gib-core"]

[dependencies]
clap = "2.32.0"
cpal = "0.8.2"
crossbeam = "0.7.1"
failure = "0.1.5"
gfx = "0.18"
gfx_core = "0.9.2"
gfx_device_gl = "0.16"
gfx_window_glutin = "0.30"
gib-core = {path = "gib-core"}
glutin = "0.20"
imgui = "0.1.0"
imgui-gfx-renderer = "0.1.0"
imgui-sys = "0.1.0"
imgui-winit-support = "0.1.0"

[profile.dev]
debug = false
opt-level = 3
overflow-checks = false
