[package]
authors = ["Pietro Lorefice <pietro.lorefice@gmail.com>"]
description = "A Game Boy emulator written in Rust"
edition = "2018"
name = "gib"
version = "0.5.2"

[workspace]
members = ["gib-core"]

[dependencies]
clap = "2.33.3"
cpal = "0.13.3"
crossbeam = "0.8.1"
failure = "0.1.8"
gfx = "0.18.2"
gfx_device_gl = "0.16.2"
gib-core = {path = "gib-core"}
glutin = "0.26"
imgui = "0.7.0"
imgui-gfx-renderer = "0.7.0"
imgui-sys = "0.7.0"
imgui-winit-support = "0.7.1"
old_school_gfx_glutin_ext = "0.26"

[profile.dev]
debug = false
opt-level = 3
overflow-checks = false
