[package]
authors = ["Pietro Lorefice <pietro.lorefice@gmail.com>"]
description = "A Game Boy emulator written in Rust"
edition = "2018"
name = "gib"
version = "0.5.2"

[workspace]
members = ["gib-core"]

[dependencies]
anyhow = "1.0.41"
clap = "2.33.3"
cpal = "0.13.3"
crossbeam = "0.8.1"
gib-core = {path = "gib-core"}
imgui = "0.7.0"
imgui-wgpu = "0.15.1"
imgui-winit-support = "0.7.1"
pollster = "0.2.4"
wgpu = "0.8.1"
winit = "0.24.0"

[profile.dev]
debug = false
opt-level = 3
overflow-checks = false
