version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Install devtools
          command: |
            sudo apt update
            sudo apt install libasound2-dev
      - run:
          name: Version information
          command: |
            rustc --version --verbose
            cargo --version --verbose
      - run:
          name: Build
          command: cargo build --release
      - run:
          name: Run tests
          command: cargo test --release --all