[package]
authors = ["Pietro Lorefice <pietro.lorefice@gmail.com>"]
description = "A low-level, cycle-accurate Game Boy emulation library"
edition = "2018"
name = "gib-core"
version = "0.5.2"

[dependencies]
bitflags = "1.2.1"
crossbeam = "0.8.1"
failure = "0.1.8"
